import type { SimpleIcon } from "simple-icons";
import {
  siPython,
  siJavascript,
  siCplusplus,
  siHtml5,
  siCss,
  siReact,
  siNextdotjs,
  siTypescript,
  siAndroidstudio,
  siKotlin,
  siFirebase,
  siNodedotjs,
  siExpress,
  siFastapi,
  siFlask,
  siMlflow,
  siDvc,
  siApacheairflow,
  siPrometheus,
  siGrafana,
  siScikitlearn,
  siDocker,
  siKubernetes,
  siJenkins,
  siGithubactions,
  siMongodb,
  siMysql,
  siPostgresql,
  siFigma,
  siDiagramsdotnet,
  siProteus,
  siUml,
  siGit,
} from "simple-icons";

// Keyed by the exact simpleIconSlug strings used in data/skills.ts. A number
// of real skills genuinely have no brand glyph in this simple-icons version
// (Java, C#-style trademark casualties like AWS/LinkedIn) - Java, SQL,
// SQL Server, Canva, Adobe Photoshop, and Pencil all checked and confirmed
// absent 2026-07-18. Those render text-only, same as any other non-brand
// entry - not an oversight.
export const SIMPLE_ICONS: Record<string, SimpleIcon> = {
  python: siPython,
  javascript: siJavascript,
  cplusplus: siCplusplus,
  html5: siHtml5,
  css: siCss,
  react: siReact,
  nextdotjs: siNextdotjs,
  typescript: siTypescript,
  androidstudio: siAndroidstudio,
  kotlin: siKotlin,
  firebase: siFirebase,
  nodedotjs: siNodedotjs,
  express: siExpress,
  fastapi: siFastapi,
  flask: siFlask,
  mlflow: siMlflow,
  dvc: siDvc,
  apacheairflow: siApacheairflow,
  prometheus: siPrometheus,
  grafana: siGrafana,
  scikitlearn: siScikitlearn,
  docker: siDocker,
  kubernetes: siKubernetes,
  jenkins: siJenkins,
  githubactions: siGithubactions,
  mongodb: siMongodb,
  mysql: siMysql,
  postgresql: siPostgresql,
  figma: siFigma,
  diagramsdotnet: siDiagramsdotnet,
  proteus: siProteus,
  uml: siUml,
  git: siGit,
};
